/**
 * InsightsPanel Component
 *
 * Displays contextual, actionable insights generated by the insights service.
 * Shows persona-specific recommendations based on analysis results.
 */

import React, { useState, useEffect } from 'react';
import type { QueryResponse, CausalAnalysisResult, BayesianBeliefState, GuardianDecision } from '../../types/carf';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

interface InsightsPanelProps {
    queryResponse: QueryResponse | null;
    causalResult?: CausalAnalysisResult | null;
    bayesianResult?: BayesianBeliefState | null;
    guardianResult?: GuardianDecision | null;
    persona?: 'analyst' | 'developer' | 'executive';
    className?: string;
    maxInsights?: number;
}

interface Insight {
    id: string;
    type: 'improvement' | 'warning' | 'opportunity' | 'recommendation' | 'explanation' | 'validation';
    priority: 'high' | 'medium' | 'low';
    title: string;
    description: string;
    action: string | null;
    related_component: string | null;
}

const typeIcons: Record<string, string> = {
    improvement: '🔧',
    warning: '⚠️',
    opportunity: '💡',
    recommendation: '📋',
    explanation: '📖',
    validation: '✅',
};

const typeColors: Record<string, { bg: string; border: string; text: string }> = {
    improvement: { bg: 'bg-blue-50 dark:bg-blue-900/30', border: 'border-blue-200 dark:border-blue-700', text: 'text-blue-700 dark:text-blue-300' },
    warning: { bg: 'bg-red-50 dark:bg-red-900/30', border: 'border-red-200 dark:border-red-700', text: 'text-red-700 dark:text-red-300' },
    opportunity: { bg: 'bg-green-50 dark:bg-green-900/30', border: 'border-green-200 dark:border-green-700', text: 'text-green-700 dark:text-green-300' },
    recommendation: { bg: 'bg-purple-50 dark:bg-purple-900/30', border: 'border-purple-200 dark:border-purple-700', text: 'text-purple-700 dark:text-purple-300' },
    explanation: { bg: 'bg-gray-50 dark:bg-gray-800/30', border: 'border-gray-200 dark:border-gray-700', text: 'text-gray-700 dark:text-gray-300' },
    validation: { bg: 'bg-emerald-50 dark:bg-emerald-900/30', border: 'border-emerald-200 dark:border-emerald-700', text: 'text-emerald-700 dark:text-emerald-300' },
};

const priorityColors: Record<string, string> = {
    high: 'bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300',
    medium: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300',
    low: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
};

const InsightsPanel: React.FC<InsightsPanelProps> = ({
    queryResponse,
    causalResult,
    bayesianResult,
    guardianResult,
    persona = 'analyst',
    className = '',
    maxInsights = 5,
}) => {
    const [insights, setInsights] = useState<Insight[]>([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [expandedId, setExpandedId] = useState<string | null>(null);
    const [filterType, setFilterType] = useState<string | null>(null);

    // Fetch insights from API
    useEffect(() => {
        const fetchInsights = async () => {
            if (!queryResponse) {
                setInsights([]);
                return;
            }

            setLoading(true);
            setError(null);

            try {
                const response = await fetch(`${API_BASE_URL}/insights/generate`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        persona,
                        domain: queryResponse.domain,
                        domain_confidence: queryResponse.domainConfidence,
                        domain_entropy: queryResponse.domainEntropy,
                        has_causal_result: !!causalResult,
                        causal_effect: causalResult?.effect,
                        refutation_pass_rate: causalResult?.refutationsTotal
                            ? (causalResult.refutationsPassed || 0) / causalResult.refutationsTotal
                            : null,
                        has_bayesian_result: !!bayesianResult,
                        epistemic_uncertainty: bayesianResult?.epistemicUncertainty,
                        aleatoric_uncertainty: bayesianResult?.aleatoricUncertainty,
                        guardian_verdict: queryResponse.guardianVerdict,
                        policies_passed: guardianResult?.policiesPassed || 0,
                        policies_total: guardianResult?.policiesTotal || 0,
                    }),
                });

                if (response.ok) {
                    const data = await response.json();
                    setInsights(data.insights || []);
                } else {
                    throw new Error('Failed to fetch insights');
                }
            } catch (err) {
                console.error('Failed to fetch insights:', err);
                setError('Unable to load insights');
                // Generate fallback insights based on available data
                setInsights(generateFallbackInsights(queryResponse, causalResult, bayesianResult));
            } finally {
                setLoading(false);
            }
        };

        fetchInsights();
    }, [queryResponse, causalResult, bayesianResult, guardianResult, persona]);

    // Generate fallback insights when API is unavailable
    const generateFallbackInsights = (
        qr: QueryResponse | null,
        cr: CausalAnalysisResult | null | undefined,
        br: BayesianBeliefState | null | undefined
    ): Insight[] => {
        const fallback: Insight[] = [];

        if (qr) {
            // Domain confidence insight
            const confidence = (qr.domainConfidence || 0) * 100;
            if (confidence < 70) {
                fallback.push({
                    id: 'fb-1',
                    type: 'warning',
                    priority: 'high',
                    title: 'Low domain confidence',
                    description: `Classification confidence is ${confidence.toFixed(0)}%. Results should be interpreted with caution.`,
                    action: 'Provide more context in your query for better classification.',
                    related_component: 'cynefin_router',
                });
            } else if (confidence >= 85) {
                fallback.push({
                    id: 'fb-2',
                    type: 'validation',
                    priority: 'low',
                    title: 'High confidence analysis',
                    description: `The analysis achieved ${confidence.toFixed(0)}% classification confidence.`,
                    action: null,
                    related_component: 'cynefin_router',
                });
            }

            // Causal analysis insights
            if (cr && cr.refutationsTotal && cr.refutationsTotal > 0) {
                const passRate = ((cr.refutationsPassed || 0) / cr.refutationsTotal) * 100;
                if (passRate < 80) {
                    fallback.push({
                        id: 'fb-3',
                        type: 'warning',
                        priority: 'high',
                        title: 'Causal robustness concerns',
                        description: `Only ${passRate.toFixed(0)}% of refutation tests passed.`,
                        action: 'Review the causal graph and consider additional confounders.',
                        related_component: 'causal_analyst',
                    });
                }
            }

            // Bayesian uncertainty insights
            if (br && (br.epistemicUncertainty || 0) > 0.3) {
                fallback.push({
                    id: 'fb-4',
                    type: 'opportunity',
                    priority: 'medium',
                    title: 'Reducible uncertainty detected',
                    description: `Epistemic uncertainty of ${((br.epistemicUncertainty || 0) * 100).toFixed(0)}% can be reduced with more data.`,
                    action: 'Consider collecting additional samples or running experiments.',
                    related_component: 'bayesian_explorer',
                });
            }
        }

        return fallback;
    };

    const filteredInsights = filterType
        ? insights.filter(i => i.type === filterType)
        : insights;

    const displayInsights = filteredInsights.slice(0, maxInsights);
    const uniqueTypes = [...new Set(insights.map(i => i.type))];

    if (!queryResponse) {
        return (
            <div className={`p-6 bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 ${className}`}>
                <div className="text-center text-gray-500 dark:text-slate-400">
                    <span className="text-3xl mb-2 block">💡</span>
                    <p className="text-sm">Run an analysis to see contextual insights</p>
                </div>
            </div>
        );
    }

    return (
        <div className={`bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 ${className}`}>
            {/* Header */}
            <div className="p-4 border-b border-gray-200 dark:border-slate-700">
                <div className="flex items-center justify-between">
                    <h3 className="font-semibold text-gray-900 dark:text-slate-100 flex items-center gap-2">
                        <span>💡</span>
                        Insights for {persona.charAt(0).toUpperCase() + persona.slice(1)}s
                    </h3>
                    <span className="text-xs text-gray-500 dark:text-slate-400">
                        {insights.length} insight{insights.length !== 1 ? 's' : ''}
                    </span>
                </div>

                {/* Type filters */}
                {uniqueTypes.length > 1 && (
                    <div className="flex gap-1 mt-3 flex-wrap">
                        <button
                            onClick={() => setFilterType(null)}
                            className={`px-2 py-1 text-xs rounded-full transition-colors ${
                                filterType === null
                                    ? 'bg-primary text-white'
                                    : 'bg-gray-100 dark:bg-slate-700 text-gray-600 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-600'
                            }`}
                        >
                            All
                        </button>
                        {uniqueTypes.map(type => (
                            <button
                                key={type}
                                onClick={() => setFilterType(type)}
                                className={`px-2 py-1 text-xs rounded-full transition-colors capitalize ${
                                    filterType === type
                                        ? 'bg-primary text-white'
                                        : 'bg-gray-100 dark:bg-slate-700 text-gray-600 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-600'
                                }`}
                            >
                                {typeIcons[type]} {type}
                            </button>
                        ))}
                    </div>
                )}
            </div>

            {/* Content */}
            <div className="p-4">
                {loading && (
                    <div className="flex items-center justify-center py-8">
                        <div className="animate-spin w-6 h-6 border-2 border-primary border-t-transparent rounded-full" />
                    </div>
                )}

                {error && (
                    <div className="p-3 bg-yellow-50 dark:bg-yellow-900/30 border border-yellow-200 dark:border-yellow-700 rounded-lg text-sm text-yellow-700 dark:text-yellow-300 mb-3">
                        {error}
                    </div>
                )}

                {!loading && displayInsights.length === 0 && (
                    <div className="text-center text-gray-500 dark:text-slate-400 py-8">
                        <span className="text-2xl block mb-2">✨</span>
                        <p className="text-sm">No specific insights for this analysis</p>
                    </div>
                )}

                {!loading && displayInsights.length > 0 && (
                    <div className="space-y-3">
                        {displayInsights.map(insight => {
                            const colors = typeColors[insight.type] || typeColors.explanation;
                            const isExpanded = expandedId === insight.id;

                            return (
                                <div
                                    key={insight.id}
                                    className={`p-3 rounded-lg border cursor-pointer transition-all ${colors.bg} ${colors.border} ${
                                        isExpanded ? 'shadow-md' : 'hover:shadow-sm'
                                    }`}
                                    onClick={() => setExpandedId(isExpanded ? null : insight.id)}
                                >
                                    <div className="flex items-start justify-between gap-2">
                                        <div className="flex items-center gap-2 flex-1 min-w-0">
                                            <span className="text-lg flex-shrink-0">{typeIcons[insight.type]}</span>
                                            <div className="flex-1 min-w-0">
                                                <div className="font-medium text-gray-900 dark:text-slate-100 text-sm truncate">
                                                    {insight.title}
                                                </div>
                                            </div>
                                        </div>
                                        <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full uppercase flex-shrink-0 ${priorityColors[insight.priority]}`}>
                                            {insight.priority}
                                        </span>
                                    </div>

                                    {isExpanded && (
                                        <div className="mt-3 pt-3 border-t border-gray-200/50 dark:border-slate-600/50 space-y-2">
                                            <p className={`text-sm ${colors.text}`}>
                                                {insight.description}
                                            </p>
                                            {insight.action && (
                                                <p className="text-sm font-medium text-primary dark:text-primary-light">
                                                    → {insight.action}
                                                </p>
                                            )}
                                            {insight.related_component && (
                                                <p className="text-xs text-gray-500 dark:text-slate-500">
                                                    Related: {insight.related_component}
                                                </p>
                                            )}
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                )}

                {filteredInsights.length > maxInsights && (
                    <div className="mt-3 text-center">
                        <button className="text-sm text-primary hover:underline">
                            View all {filteredInsights.length} insights
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default InsightsPanel;
